=== Vignesh-24/Training/excelPDF/bill.dtd
<!ELEMENT items (item+)>
<!ELEMENT item (id,name,unit,price,qty,amount)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT unit (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT qty (#PCDATA)>
<!ELEMENT amount (#PCDATA)>

=== Vignesh-24/Training/excelPDF/bill.xml
<!DOCTYPE items SYSTEM "bill.dtd">
<items>
	<item>
		<id>1</id>
		<name>Daal</name>
		<unit>1</unit>
		<price>40</price>
		<qty>3</qty>
		<amount>120</amount>
	</item>
	<item>
		<id>2</id>
		<name>Rice</name>
		<unit>1</unit>
		<price>50</price>
		<qty>10</qty>
		<amount>500</amount>
	</item>
	<item>
		<id>3</id>
		<name>Sugar</name>
		<unit>1</unit>
		<price>50</price>
		<qty>5</qty>
		<amount>250</amount>
	</item>
</items>
